export const STUDENTS = [
  {
    name: 'Селиван',
    surname: 'Литвинов',
    patronymic: 'Константинович',
    dob: new Date('1994-06-03'),
    startStudiesYear: 2012,
    faculty: 'Горно-геологический',
  },
  {
    name: 'Евгения',
    surname: 'Кондратьева',
    patronymic: 'Антоновна',
    dob: new Date('1992-01-25'),
    startStudiesYear: 2012,
    faculty: 'Кибернетики и автоматики',
  },
  {
    name: 'Михаил',
    surname: 'Арсеньев',
    patronymic: 'Викторович',
    dob: new Date('1984-11-24'),
    startStudiesYear: 2021,
    faculty: 'Сельскохозяйственный',
  },
  {
    name: 'Егор',
    surname: 'Баранов',
    patronymic: 'Альбертович',
    dob: new Date('1998-11-14'),
    startStudiesYear: 2015,
    faculty: 'Архитектуры и дизайна',
  },
  {
    name: 'Дарина',
    surname: 'Емельянова',
    patronymic: 'Егоровна',
    dob: new Date('1979-09-30'),
    startStudiesYear: 2004,
    faculty: 'Кибернетики и автоматики',
  },
  {
    name: 'Исай',
    surname: 'Соколович',
    patronymic: 'Викторович',
    dob: new Date('1987-04-21'),
    startStudiesYear: 2004,
    faculty: 'Архитектуры и дизайна',
  },
];
